name: message-logger
main: net.twasiplugin.messagelogger.MessageLoggerPlugin
author: Twasi Team
description: Logs all messages (and other events) of every chat
version: '1.0'

hidden: true
autoInstall: true

commands: